### ISSUE TITLE
Setup Basic Layout

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#1]
The basic layout should consist of:
- a tab bar with 5 items (in order): Home, Category filter, Search, My Account, Cart(/Bag)
- a navigation bar

TODO:
- Provide assets for tab bar (Home and Category filter), but not MVP, we can work with the search tab to show POP
- Ask about how to show enabled tabs (see discussion below), in short: iOS guidelines suggest to have all buttons same color/behaviour, which doesn't fit with the yellow version of "my bag". Also, we would need in any case some way to show selected/non-selected tabs.

**Comment by lauraluiz** [comment]
Tab bar with these colors and assets:
<img width="975" alt="screen shot 2016-05-11 at 17 56 37" src="https://cloud.githubusercontent.com/assets/1917621/15187545/c383adba-17a1-11e6-8f45-204d7578740a.png">
- Only Search, Cart and Customer icons remain.
- Missing Home and Category filter icons.

**Comment by lauraluiz** [comment]
Navigation bar with same background color as the tab bar (dark blue)

**Comment by lauraluiz** [comment]
@nikola-mladenovic how is the font support in iOS apps?

**Comment by nikola-mladenovic** [comment]
We can use anything we choose. Some apps have custom fonts, while others use system font, and the benefit is that your app automatically adopts new system font on the new iOS version. Would would be our preference for Sunrise?

**Comment by lauraluiz** [comment]
System font family sounds good enough IMO, it will make everything simpler. And it sounds like they can keep the application nice for a longer time, which is also good.

**Comment by nikola-mladenovic** [comment]
@lauraluiz - the iOS tab bar guideline for selected icon are a different then what we have on the website. On the web, when icon is selected the background changes the color to yellow, while iOS tab bar default behavior is to change the image tint:

Selected:
<img width="40" alt="screen shot 2016-05-13 at 12 00 58 pm" src="https://cloud.githubusercontent.com/assets/14024032/15244907/d58babf8-1903-11e6-9467-a44b09144fae.png">

Not selected:
<img width="35" alt="screen shot 2016-05-13 at 12 11 58 pm" src="https://cloud.githubusercontent.com/assets/14024032/15244924/f02c2172-1903-11e6-98f5-86f258d99e79.png">

Do you agree with this?

**Comment by lauraluiz** [comment]
What will happen with my cart, which is yellow background and dark icon?

**Comment by nikola-mladenovic** [comment]
Ah, good question. At first I thought that the cart icon is "active" and that's why it has yellow background. But now, I tried using Sunrise web app on my phone, and I see we don't have any indication of the active tab.

If we decide to go according to the iOS guidelines, we want to have the same behavior for all icons.
And if we decide to do something similar to the web version, we'd to decide how to mark the active tab icon.

**Comment by lauraluiz** [comment]
Maybe it's something we can address the designer. Otherwise, I would go for removing the yellow color from the bag and follow the highlighted from iOS. It's my fallback option because I would try to avoid changing the design.
