### ISSUE TITLE
Reservation "order" creation

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#10]
If the user is logged in, a `Reserve in Store` button should be displayed for each store. 
If clicked, it adds the item along with the channel to the cart and creates an order.

The order should:
- Contain the item associated with the channel.
- Have the custom type for click&reserve use case (which contains the `clickandreserve` custom field, empty) (read TODO).
- Generate an order number with some kind of prefix to distinguish from regular orders (read TODO).

Once order is created, it will transition to `My Account - My Reservations` to the overview of the reservation.

As the user must be logged in, we will ignore for now the case of anonymous reservation. In any case, in the future a form will be displayed to fill your name, email and maybe phone number and create an anonymous reservation "order".

TODO:
- Add Custom Type with custom field `clickandreserve` to the data and some snippet to generate for any project.
- Decide how to generate order number

**Comment by lauraluiz** [comment]
Instead of Checkout message, put "Reserve now" message.

![screen shot 2016-05-12 at 17 47 00](https://cloud.githubusercontent.com/assets/1917621/15220923/91af1fae-1869-11e6-86ad-b7d9638a0616.png)

**Comment by lauraluiz** [comment]
Remember to generate an order number (I guess the best you can do for now is generate a random 8-digit number).

**Comment by nikola-mladenovic** [comment]
The custom type for reservations should contain:
- `channel` reference
- `availableAfter` ? (depending on the use case)
