### ISSUE TITLE
Save device token in a customer custom type custom field

### ISSUE THREAD

**Issue by nikola-mladenovic** [commercetools/commercetools-sunrise-ios#109]
For purposes of pushing reservation confirmation notifications, we'd like to store device token in a custom field. The payload used to create custom type containing `apnsToken` custom field:

```
{
   "key":"iOSUser",
   "name":{
      "de":"iOSUser",
      "en":"iOSUser"
   },
   "resourceTypeIds":[
      "customer"
   ],
   "fieldDefinitions":[
      {
         "type":{
            "name":"String"
         },
         "name":"apnsToken",
         "required":false,
         "label":{
            "de":"apnsToken",
            "en":"apnsToken"
         }
      }      
   ]
}
```

The token should be saved when the user logs in, each time it starts the app, and removed when the user logs out.

@cneijenhuis - do you agree with the custom type layout?

**Comment by cneijenhuis** [comment]
I would rather call it `iOSUser`, or so. Otherwise 👍

**Comment by nikola-mladenovic** [comment]
Makes sense 👍
