### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#11]
The Login View should allow the user to login with his credentials.

**Comment by lauraluiz** [comment]
Change text to: "If you have an account, please sign in to reserve in store."
Change button: "Quick checkout" to "Sign In"

![screen shot 2016-05-12 at 17 52 08](https://cloud.githubusercontent.com/assets/1917621/15221091/4769aa8a-186a-11e6-8abd-5bc969be6e8e.png)
