### ISSUE TITLE
Translate into German

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#111]

**Comment by nkuehn** [comment]
If someone provides the explanation how to do it safely I offer to "just do it" as an initial version.  
Have XCode etc. running, just not real experience with it.

**Comment by nikola-mladenovic** [comment]
Actually you won't have to bother with installing any tools - I'll just send you a couple of files similar to
https://github.com/commercetools/commercetools-sunrise-ios/blob/master/Sunrise/de.lproj/Localizable.strings

where we have the English version, and you just fill in the German one.

Many thanks for offering to help with this one! 🎉

**Comment by nkuehn** [comment]
better do a branch and check it in.

**Comment by nkuehn** [comment]
You don't even need to provide the prepared file.  I used the XLIFF export of Xcode and found a simple free translation tool. 

https://itunes.apple.com/lv/app/xlifftool/id1074282695?mt=12 

That's the standard workflow as documented by Apple anyways.

**Comment by nkuehn** [comment]
here you go (zipped because GitHub does not accept the .xliff extension. 

[de.xliff.zip](https://github.com/commercetools/commercetools-sunrise-ios/files/992795/de.xliff.zip)

Please let another native speaker (e.g. @cneijenhuis  or @mmoelli)   review the wording - just reading is pretty simple and if you do it in the XLIFF editor easy, too because you see the original, the translation, the component and the developer comment side-by-side.

**Comment by nikola-mladenovic** [comment]
@nkuehn - many thanks for investing the time in these translations!

I went through the ones you uploaded, and created a new .xliff file with some cases which were missing.
They're all located under 'Sunrise/Storyboard' directory, and I suggest you filter for non-translated.
Feel free to ignore all other non-translated that aren't under 'Sunrise/Storyboard' directory.

[de.xliff.zip](https://github.com/commercetools/commercetools-sunrise-ios/files/1001750/de.xliff.zip)

As soon as we incorporate the missing ones, I'm going to upload a TestFlight build for @cneijenhuis and @mmoelli

**Comment by nkuehn** [comment]
OK, probably did the export the wrong way or in the wrong context in XCode. 

For clarification my assumptions:
 * not translating stuff like "streetAndNumber" which isn't a user visible text anyways / obviously
 * not translating numbers whose formatting is not different ("37")
 * not translating placeholders like ${PRODUCT_NAME}
 * keeping ALL CAPS text  in GROSSBUCHSTABEN    (didn't do that right in the last file). 

Question:  Also keep padded whitespace e.g. like in " ADD TO BAG" ?  or is that a bug? 

A thing we should consider changing:  If you want certain text snippets capitalized IMHO that should be part of the style information in the implementation and not in the content.   At least that's how I see it as a best practice in Web / CSS implementations. 

Let's document the practice in the README once clear.

**Comment by nikola-mladenovic** [comment]
> OK, probably did the export the wrong way or in the wrong context in XCode.

You did everything right, it's just the fact those storyboard files didn't have German locale turned on at that point.

> not translating stuff like "streetAndNumber" which isn't a user visible text anyways / obviously
not translating numbers whose formatting is not different ("37")
not translating placeholders like ${PRODUCT_NAME}

👍 

> keeping ALL CAPS text in GROSSBUCHSTABEN (didn't do that right in the last file).

Not a problem, I will update them.

>  If you want certain text snippets capitalized IMHO that should be part of the style information in the implementation and not in the content.

> Question: Also keep padded whitespace e.g. like in " ADD TO BAG" ? or is that a bug?

I'd say keep it if it's not an issue for you. Even if you don't I'll def go through the file and add it. In this example, the whitespace is added to gain more space between the button icon, and the button text. It can also be done in the code, but this way it saves a few lines in the view controller.

> If you want certain text snippets capitalized IMHO that should be part of the style information in the implementation and not in the content.

Generally speaking, I do completely agree. The iOS approach differs a bit from the Web / CSS paradigm: you have a storyboard file, where you can go ahead and set the values for the labels that are not supposed to be changed programmatically. In case you want to set the text value for a particular label in the storyboard, and have the "style" part saying whether it should be uppercase / lowercase / first letter upper, etc.. you'd have to create IBOutlets for every single one, and then update the 'style' in the view controller.
It'd be great if storyboard had a declaration for text-transform, so it'd be another property to be set there, without adding a lot of code to your view controllers.

Now when we've started to localize these labels, it makes sense not to bother you with this practice. I'll go ahead and double check how many "differently styled" labels we have.
You can feel free to submit the translation either way, I will go through them 👍

**Comment by nkuehn** [comment]
OK, understood the pricinple.  It's much less code boilerplate work to do it in the translation files for now.  For the current development phase of the app we should focus on getting features out, so let's stick with doing stuff in trans files.

**Comment by nkuehn** [comment]
Here you go.  

[de2.xliff.zip](https://github.com/commercetools/commercetools-sunrise-ios/files/1003942/de2.xliff.zip)

I could not find / did not understand this one from the Comments:
"Browsing Options"

FYI: this file was massively redundant in comparison to the first texts (esp. the Checkout).  Not sure if there is a concept for re-use in the Strings system. Maybe this is the Reason why "Translation Memory" is such a big thing in Translation services.
