### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#12]
The Signup View should allow the user to signup with email and password.

There should be a switch between the Login View and the Signup View.

**Comment by lauraluiz** [comment]
This is low priority and not MVP. But if you have time:
- ignore newsletter stuff
- notice it goes below sign in

![screen shot 2016-05-12 at 18 17 40](https://cloud.githubusercontent.com/assets/1917621/15221943/da52cc34-186d-11e6-930e-775682d73461.png)
