### ISSUE TITLE
My Account

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#13]
If not logged in, the login view / signup view should be displayed if the My Account View is requested via the tab bar.

If logged in, a list of orders should be displayed.
- The list should include the date of the order and the total amount.
- It is sorted by date.
- All orders without custom field `clickandreserve` defined (otherwise they are reservations).

If clicked on an order, the Order View should be displayed. It is the same as the view for carts.

**Comment by lauraluiz** [comment]
Overview of the structure (only keep "my orders" and "sign out" tabs)
Just ignore the content of the order here and use the same as in cart, as mentioned.
![screen shot 2016-05-12 at 17 58 57](https://cloud.githubusercontent.com/assets/1917621/15221504/febe1c6a-186b-11e6-9334-be8d3001e262.png)

For the list of orders, it should look like this (ignore the fact that they did this for returns, just put Order Number, Total Price and the View button):
![screen shot 2016-05-12 at 18 12 45](https://cloud.githubusercontent.com/assets/1917621/15221793/2ea55dd4-186d-11e6-9a00-7664ab676642.png)

**Comment by nikola-mladenovic** [comment]
@lauraluiz - when the user taps on the view button, should we take him to the different screen and show order details, or do another expansion in the same screen? Maybe the first option would be better, so we don't have 3 levels of expansions in the same screen?

**Comment by lauraluiz** [comment]
@nikola-mladenovic yes, I think in mobile it's better as you suggest. But then we have to change the `+` with `>`.

**Comment by lauraluiz** [comment]
Definitely to a new view.
Regarding the collapsable sections in my account, does it work well with the app? If you have a long list you can easily get lost within the sections. How is your experience in that sense?
