### ISSUE TITLE
Remove "MRS." Title option

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sunrise-ios#151]
differentiating "MRS."   or in German "Fräulein" to "MS." or in German "Frau" is not considered politically correct any more, also for privacy reasons (we have no need to know the maritial status). 

It may be standard in the UK still, but I vote to not offer that option any more. 

If we feel progressive we could offer "other" and free text input for whatever non-binary gender people feel they are.

**Comment by nikola-mladenovic** [comment]
I do agree with you - my reasoning was just to copy the options from the Sunrise website. I guess we change this in both places?

**Comment by nkuehn** [comment]
Not sure if we need to create that hard dependency - but yes, an issue entry should be there in the Java version and the view code needs to be robust against any value anyways since it's a free text field in the API .

**Comment by nikola-mladenovic** [comment]
The view code should be fine - the customer will be able to see the same profile details on both sides, just won't be able to set the same value until we sync (after this change), because it's a drop down with predefined values.
