### ISSUE TITLE
Include PSP

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-ios#155]
As a User, I want to be offered multiple payment options from well known payment providers, so that I can complete my checkout without hesitation.

- blocked by missing API endpoint: /payments/me
- Use of PAYONE integration

**Comment by nikola-mladenovic** [comment]
Not sure if it directly impacts this integration, but the /payments endpoint is not yet available to mobile (or SPA) clients.

**Comment by mmoelli** [comment]
true that, updated the issue.
