### ISSUE TITLE
Support discount code 

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-ios#156]
As a User, I want to enter a discount code in the checkout, so that I can buy products for a discounted price.

- Enable enter code on final checkout page
- show correctly the discounted value
- show the discount each code is generating

**Comment by nikola-mladenovic** [comment]
I was looking to find the place on the final checkout page to add the discount codes support, but it seems that the better place might be on the first cart screen, because that's the place where we show line items, prices, and line item / cart discounts.

WDYT @mmoelli ?

**Comment by mmoelli** [comment]
Would be an option, but we actually have to redesign the final page anyway. Problem here is, there is a German law, that you have to show the final price on the page which also has the final Buy button. 

But I guess for now, the cart page is the best option here.

**Comment by nikola-mladenovic** [comment]
Good point, I wasn't aware of that fact, and we will bring it up to the designer for sure.

> But I guess for now, the cart page is the best option here.

👍
