### ISSUE TITLE
Change category tree root

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-ios#157]
As a Category Manager, I want to define a specific category as root category for my navigation, so that I can use the categories also for non-navigational tasks.

- see [Sunrise Java](https://github.com/commercetools/commercetools-sunrise-java/issues/419)

**Comment by nikola-mladenovic** [comment]
@mmoelli - in addition to the `navigationExternalId` which practically represents the tree root you described above, Sunrise Java provides some additional options:
```
# Key from the cache where to store the category tree.
cacheKey = "categoryTree"

# Time in seconds until the category tree in cache expires.
# If undefined no expiration is set.
# cacheExpiration = 3600

# List (for multisort) of sort expressions applied when querying the categories.
# In CTP format (http://dev.commercetools.com/http-api.html#sorting) for Category Query.
sortExpressions = []

# Defines whether the categories with no products assigned should be discarded from the navigation category tree.
# Set to false to keep all categories.
discardEmpty = false

# External ID of the category in your CTP project which children represent the navigation category tree displayed to the user.
# If undefined the whole category tree from your CTP project is used as navigation.
# navigationExternalId = "navigation"

# External ID of the category in your CTP project to which any product tagged as new is associated.
# If undefined no product will be displayed as new.
# newExternalId = "new"

# List of navigation categories that do not display all products associated with these categories.
# Instead they will use the given filter expressions to display products.
# If empty all categories will display their associated products.
specialCategories = []
```

Should we just focus on the tree root, or add some of these additional options?

**Comment by mmoelli** [comment]
- How is the cache invalidation currently working?
- Sorting we could stay as it is?
- Discarding empty categories would only possible via GraphQL implementation, do we want to touch this?
- New and Special categories I would not implement yet.

**Comment by nikola-mladenovic** [comment]
- Cache is valid throughout the app's lifecycle; the assumption was the app's life is shorter than the timeframe in which the categories are likely to be changed;
- We're not passing any sort parameter at the moment;
- We could if we'd gain some product value - if not I'd leave it for later;
- Agreed 👍

**Comment by mmoelli** [comment]
- Ok, maybe a max 3600s = 1h is a good default value for cache invalidation. So I would recommend to do this
- Sort I would set to "lastModifiedAt desc" to always see the latest changes on top by default. ATM, we don't need to make this editable

**Comment by nikola-mladenovic** [comment]
Makes sense 👍 

Another idea for cache invalidation, we could do something very efficient - subscribe to `CategoryCreated` and `CategorySlugChanged` messages, which would trigger a background notification (not visible to the customer), and let the app know it needs to refresh the category tree.

The downside - we don't have messages when other category update actions are performed.

So (at least for now), let's use 1h period for invalidation.

**Comment by mmoelli** [comment]
After some discussions we decided to go with a rather simple approach for now regarding cache invalidation. We will use 3600s as default value for now.
