### ISSUE TITLE
Categories are not longer working (after the last app update)

### ISSUE THREAD

**Issue by lgiavedoni** [commercetools/commercetools-sunrise-ios#165]
Hi

Version: 0.1 (97)
Project: AEM
Issue: Since the last update (a week ago) the category view is not longer working.

Thanks

**Comment by nikola-mladenovic** [comment]
Thanks for reporting this one. The underlying issue was related to `key` not being marked as optional on `AssetSource` struct. Check out the TestFlight build # 99.

**Comment by lgiavedoni** [comment]
Thanks @nikola-mladenovic, how can I get that version? In my testFlight account I still have 97.

**Comment by nikola-mladenovic** [comment]
The archive is still being processed, should be available to you within an hour or two.

**Comment by lgiavedoni** [comment]
Works! Thanks
