### ISSUE TITLE
Optimize demo functionality of app

### ISSUE THREAD

**Issue by skyriakou** [commercetools/commercetools-sunrise-ios#173]
### What?
Make sure that app interactions are producing relevant results

### Why?
So that our sales colleagues can display the capability of our APIs in a more seamless manner

### Areas that seem to have issues:

**Checkout**
Apple Pay - leads to a loading but no result

**Size selector**
Often empty and therefore static - add sizes for the 2 products on the home

**Product description**
Often empty and therefore static - use desktop descriptions

**"Looks" Category**
Link directly to Looks page

**Comment by nikola-mladenovic** [comment]
Checkout
- [ ] Apple Pay

Size selector
- [x] Add sizes for the 2 products on the home

Product description
- [x] use desktop descriptions

"Looks" Category
- [ ] Link directly to Looks page

**Comment by nikola-mladenovic** [comment]
@lauraluiz - what's the logic behind Sunrise web / SPA PDP description section (e.g screenshot bellow)?

I noticed that we don't list all attributes from the variant, but wasn't sure what's the rule (i.e which attributes to show, which not to show).

Thanks!

<img width="559" alt="Screen Shot 2019-07-26 at 4 39 32 PM" src="https://user-images.githubusercontent.com/14024032/61959556-f5460100-afc3-11e9-81ff-c9e7dce5a629.png">

**Comment by lauraluiz** [comment]
We let the developer request exactly the fields they want:
https://github.com/commercetools/sunrise-spa/blob/master/src/components/productdetail/DetailsSection.vue#L143

The template logic then iterates over whatever attributes were fetched :)

Hope it helps

**Comment by nikola-mladenovic** [comment]
Perfect, thanks @lauraluiz !

So for the Sunrise web demo that we have up & running, these are the attributes which go into _Product Details_ section: `designer`, `colorFreeDefinition`, `size`, `style`, `gender`, `articleNumberManufacturer` - correct?

**Comment by lauraluiz** [comment]
Yes, it's the only ones that made some sense to me 😄
