### ISSUE TITLE
Basic PDP

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#2]
The basic PDP should display:
- Name of the product (choose available locale, as appropriate)
- SKU
- First image of the selected variant (= for now, masterVariant)
- Price of the selected variant (= for now, masterVariant): The price without `channel`, `customerGroup`, `country` and `validUntil`/`validFrom` should be selected.
- If the selected price has `discounted` set, the discount should be displayed.

**Comment by lauraluiz** [comment]
Of course, only the stuff mentioned by @cneijenhuis. Ignore the rest.

This is the original design:
![screen shot 2016-05-12 at 17 38 25](https://cloud.githubusercontent.com/assets/1917621/15220670/97a49b24-1868-11e6-9604-b325361cfde3.png)

Discount example:
![screen shot 2016-05-12 at 17 45 26](https://cloud.githubusercontent.com/assets/1917621/15220857/5a5843a0-1869-11e6-844a-135b024bdfb7.png)

**Comment by lauraluiz** [comment]
The format of the prices can be different, flexible there. In Java we just let the money class format it according to the given locale.

**Comment by nikola-mladenovic** [comment]
@lauraluiz - which languages should our app support?

**Comment by lauraluiz** [comment]
@nikola-mladenovic so far it will just be in English. In the future we would like to support multi-language though (the languages would be given by the CTP project). So take any measure that will allow us to introduce in the future multi-language without having to change the whole code :)

**Comment by nikola-mladenovic** [comment]
👍  understood, will be using localized resources (i.e strings, UIs), so it's easy to adopt the new language.

BTW it will never be possible to support dynamic set of languages without enabling them in the iOS project before releasing. Besides the iOS project settings which need to be changed for new language, the localized files also need to be translated and added to the app bundle.

**Comment by lauraluiz** [comment]
It's perfectly fine for Sunrise iOS app.

**Comment by nikola-mladenovic** [comment]
@lauraluiz - while the image is being loaded, and in case of a network failure, we need to show some placeholder. We can either have something generic (e.g https://www.desertcart.ae/img/product-placeholder.png) or require design asset. What do you think?

**Comment by lauraluiz** [comment]
For Sunrise we have an animation that simply keeps loading even though the pic will never appear: http://sphere-sunrise.herokuapp.com/en/search?q=stone&sort=new&ppp=24&color=red
So that's the closest thing we have, but unfortunately it doesn't have a failed picture, but I'm fine with it.
It is not required for you to implement anything, but I was wondering, is there any default loading animation for iOS? Because that could be an easy fix for loading and failing. If not, I guess with something generic it will do.

Actually, the tricky part about images is to allow images of different sizes and shapes (i.e. landscape, portrait). Sunrise data can be a bit deceiving because it only has a particular shape.

**Comment by lauraluiz** [comment]
Ah and never put those "Choose size/color/whatever" if there is something already preselected. They're just annoying IMO.

**Comment by nikola-mladenovic** [comment]
When the user lands on PDP, size from master variant will be preselected, meaning we'll never have a situation that nothing's selected.

**Comment by lauraluiz** [comment]
That's why I say not to put the "choose" option, because nobody should select "choose". I know it sounds logical, but in Sunrise web we actually have some places where this Choose appears with a preselected value...

**Comment by nikola-mladenovic** [comment]
When the user lands on PDP screen, size from master variant is preselected, meaning we'll never have a state to display 'Choose' string.
