### ISSUE TITLE
Refresh cart

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-ios#27]
On pull down, the cart will be fetched again, so that the customer cart can be refreshed with latest changes, e.g. if he added something from Sunrise web.

**Comment by cneijenhuis** [comment]
Why should the cart not always be refreshed when the cart view (re-)appears?

**Comment by nikola-mladenovic** [comment]
That will also be the case. On top of that Laura would like to add pull to refresh functionality. I guess it can be useful for demos, adding some stuff on the website, and then just pulling to refresh, instead of going to a different screen and then coming back to the cart tab ☺️
