### ISSUE TITLE
Re-calculate cart

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-ios#28]
On pull down, re-calculate cart via the "Recalculate" endpoint (http://dev.commercetools.com/http-api-projects-carts.html#recalculate) so that prices are updated in case they were changed from the project.

**Comment by lauraluiz** [comment]
@cneijenhuis is it feasible to implement this endpoint in the SDK?

**Comment by cneijenhuis** [comment]
http://dev.commercetools.com/http-api-projects-me-carts.html#recalculate it's available via the /me/carts updates, which are available in the SDK (there are no models for this, as with response objects, but the endpoint is available).
