### ISSUE TITLE
Size selector for PDP

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#3]
On the PDP, a size selector should be displayed:
- Find all different values for `size` attribute among variants
- For each different `size`, use it as an option for the selector, displaying the size value as label
- Per default, the master variant is selected

If another variant is selected:
- The first image of that variant is displayed
- The price is updated

**Comment by lauraluiz** [comment]
Use whatever selector is better for a iOS app, don't follow the design. Just putting it here as an example.

![screen shot 2016-05-12 at 15 50 25](https://cloud.githubusercontent.com/assets/1917621/15216881/489be7c6-1859-11e6-8b58-fbea320e30a6.png)

**Comment by nikola-mladenovic** [comment]
@lauraluiz do we want to include ruler icon and size guide? If so we need that icon to be exported.

**Comment by lauraluiz** [comment]
No, we don't want any of that, those are other functionalities.
