### ISSUE TITLE
use email-specific keyboard in login screen

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-sunrise-ios#35]
The default keyboard has some usability issues (e.g. autocorrect and autocapitalization) for email adddresses, which makes it a bit hard to enter the address in the login screen. 

Would be nice to trigger the email specific keyboard that iOS offers ("UIKeyboardTypeEmailAddress" or so? )

**Comment by nikola-mladenovic** [comment]
@nkuehn - we'll include this one in the next TestFlight build later this week 😊
