### ISSUE TITLE
Add product to cart

### ISSUE THREAD

**Issue by lauraluiz** [commercetools/commercetools-sunrise-ios#37]
- Add button "Add to bag" using the design of the PDP (https://github.com/commercetools/commercetools-sunrise-ios/issues/2).
- This triggers the action that adds the product to the cart, with the given quantity.
- After the action, the user remains in the PDP.

**Comment by nikola-mladenovic** [comment]
> After the action, the user remains in the PDP.

@lauraluiz @cneijenhuis maybe it's just me, but my suggestion would be to show a popup, confirming you've just added the product to cart, and than giving you option to continue shopping, which would take you back to the POP, or go to cart overview, which would take you to the cart screen. WDYT?

**Comment by cneijenhuis** [comment]
Makes sense to me 👍
