### ISSUE TITLE
POP Basic

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#5]
Should be a collection view with a grid of two.

A collection view cell should contain:
- Thumbnail: First image of master variant
- Name of product and price/discount as on PDP

If the collection view cell is clicked, it should transition to the PDP view, and the PDP nav bar should link back to the POP.

The products should be sorted by `createdAt`.

For this story, a reasonable limit for the amount of products can be chosen.

**Comment by lauraluiz** [comment]
I have it in sunrise Java by default `createdAt`, because that's more similar to "newest".

**Comment by lauraluiz** [comment]
Just in case it affects you: have in mind this same view will be used for search, for category filtering or altogether. In the future these products will be sorted and/or filtered by more attributes such as color, brand, etc.

**Comment by lauraluiz** [comment]
Like this, but in two columns:

![screen shot 2016-05-12 at 17 43 41](https://cloud.githubusercontent.com/assets/1917621/15220813/241f260a-1869-11e6-8296-2ca013e8a9ad.png)
