### ISSUE TITLE
POP Unlimited Products

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#6]
The POP should be able to display more than a fixed limit of products.
Either, if feasible in reasonable time, implement "infinite scroll". Otherwise, implement a solution for paging.

**Comment by nikola-mladenovic** [comment]
@cneijenhuis @lauraluiz - This is the approach I'd like to take here:
- Always fetch no more than 16 products (per request);
- If the query or search user selected contains more than 16 products, others will be loaded as the user reaches the end of the collection view;
- In case the user scrolls down slowly, we fire up the request for the next 16 products while he/she is on the 7th or 8th (approx half). That way, if I don't scroll down very fast, I'll never see a loading indicator.

How does this sound to you as a spec for this issue?
