### ISSUE TITLE
Adjust orderNumber for reservations

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-ios#64]
ATM, when I reserve a product, the generated order doesn't get a orderNumber which makes it a bit tricky to identify them in the order view of the Admin Center. I would recommend to use the following pattern to have a quick overview already on the order list view.

RES-APP-`channel.key`-`order.createdAt`

WDYT? @nikola-mladenovic

**Comment by cneijenhuis** [comment]
Impossible, because an app does not have the permission to set an order number.

**Comment by cneijenhuis** [comment]
See https://sphere.atlassian.net/wiki/display/S/OrderNumbers+generated+by+API

**Comment by mmoelli** [comment]
Maybe we should discuss to enable this via API

**Comment by cneijenhuis** [comment]
`sunrise-ios` is the wrong place for the discussion.
