### ISSUE TITLE
Use customer information for billingAddress of reservation

### ISSUE THREAD

**Issue by mmoelli** [commercetools/commercetools-sunrise-ios#68]
### Background

When sending a push notification via PushTech, we want to directly address the customer with his first and last name. As the customer id is not present as reference, we need to have this information in the order object itself.
### Technical Requirements
- Use the `customer.firstName` and `customer.lastName` for `order.billingAddress.firstName` and `order.billingAddress.lastName`
- Use the following information from `defaultBillingAddress`
  - `streetName`
  - `streetNumber`
  - `postalCode`
  - `city`

**Comment by cneijenhuis** [comment]
Actually, all other fields from `defaultBillingAddress` could be used, if it exists.

If it doesn't exist, we need to add at least `country` to the address. I'd go with the channel contry then, I guess?

**Comment by mmoelli** [comment]
Yop, thanks for the additions @cneijenhuis
