### ISSUE TITLE
POP Full-text search

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#7]
The nav bar on the POP should display a Search Bar.

If a text is entered, the `product-projections/search` endpoint should be used to query for products.

TODO:
- Color inside search box (it will have dark blue background in the app instead of white, thus grey might not work well)

**Comment by lauraluiz** [comment]
Actually this endpoint should be used for any situation in the POP, since facets will always be shown (in the future) in this page, no matter if the customer arrived here from search or filtered by category.

**Comment by lauraluiz** [comment]
Similar to this, but having the background color of the nav bar (dark blue). I'd use then ligher color inside the search box, I'll have to check which one.

![screen shot 2016-05-12 at 16 30 30](https://cloud.githubusercontent.com/assets/1917621/15218157/e3961df0-185e-11e6-8733-08a343a3d1f7.png)
