### ISSUE TITLE
POP Barcode scanner

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#8]
In the Search Bar in the nav bar, on the right a button to trigger the barcode scanner should be displayed.

If clicked, the `AvCapture*` framework should be used to scan for barcodes:
- A default `AVCaptureVideoPreviewLayer` may be used
- Metadata objects of the following types may be used: `AVMetadataObjectTypeUPCECode, AVMetadataObjectTypeCode39Code, AVMetadataObjectTypeCode39Mod43Code, AVMetadataObjectTypeEAN13Code, AVMetadataObjectTypeEAN8Code, AVMetadataObjectTypeCode93Code, AVMetadataObjectTypeCode128Code, 
  AVMetadataObjectTypePDF417Code, AVMetadataObjectTypeQRCode, AVMetadataObjectTypeAztecCode`

If a string is detected, a search for a product with that `sku` should be done.
- If no product is found, an error should be displayed
- If a product is found, the PDP should open with the matching variant selected.

TODO: Asset for barcode scanner icon (should be an icon that represents a barcode being read, either by some kind of scanner or with a magnifier)

**Comment by lauraluiz** [comment]
Should be an icon that represents a barcode being read (either by some kind of scanner or with a magnifier).

**Comment by lauraluiz** [comment]
Error: Barcode not recognized
