### ISSUE TITLE
Cart without checkout

### ISSUE THREAD

**Issue by cneijenhuis** [commercetools/commercetools-sunrise-ios#9]
The cart view is currently only used to synchronize customer carts, e.g. when using the web version, or to show changes in the cart when something changes (re-calculate).

For each line item:
- Name, image, sku and size should be displayed
- The unit price, the quantity, the total price and, if applicable, product or cart discounts, should be displayed (all prices: gross)

Additionally,
- Cart discounts that don't apply to specific line items should be displayed.
- The total of the included taxes should be displayed.
- The total gross cart price should be displayed.

**Comment by lauraluiz** [comment]
Discard any element that was not mentioned in the requirements.
Don't show the `Checkout now` button

![screen shot 2016-05-12 at 17 26 08](https://cloud.githubusercontent.com/assets/1917621/15220117/a532874e-1866-11e6-9c3e-568860344557.png)

**Comment by nikola-mladenovic** [comment]
@lauraluiz @cneijenhuis - in case we get several carts for the currently logged in user, how should we display them?

**Comment by cneijenhuis** [comment]
I realized I'm missing this in the mobile API: http://dev.commercetools.com/http-api-projects-carts.html#get-cart-by-customer-id
I'll add that when I'm back.

Basically, get the cart with state `Active` which has the most recent `lastModifiedAt`.

**Comment by nikola-mladenovic** [comment]
Will do! 👍

**Comment by lauraluiz** [comment]
@cneijenhuis actually it's not a big deal. Currently this endpoint doesn't support expansion, so we use queries instead for Java and PHP, because we need to expand at certain point the shipping and payment info. Also, Fetch by ID can return non-Active carts, so in order to avoid it we simply do all queries. A pity.
